const fs = require('fs');
const file = 'src/data/registry.ts';
let content = fs.readFileSync(file, 'utf8');

const newTools = `,
  { id: "scientific-calculator", title: "Scientific Calculator", description: "Advanced scientific calculator with history and trigonometric functions.", slug: "scientific-calculator", category: "Mathematics", subcategory: "Basic Math", icon: "<svg fill='none' viewBox='0 0 24 24' stroke='currentColor' stroke-width='2'><path stroke-linecap='round' stroke-linejoin='round' d='M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z'></path></svg>", component: "ScientificCalculator" },
  { id: "simultaneous-equations", title: "Simultaneous Equation Solver", description: "Solve systems of linear equations with 2 or 3 variables.", slug: "simultaneous-equations", category: "Mathematics", subcategory: "Algebra", icon: "<svg fill='none' viewBox='0 0 24 24' stroke='currentColor' stroke-width='2'><path stroke-linecap='round' stroke-linejoin='round' d='M12 6v6m0 0v6m-6-6h12'></path></svg>", component: "SimultaneousEquations" },
  { id: "matrix-calculator", title: "Matrix Calculator", description: "Add, subtract, multiply, transpose, and invert matrices.", slug: "matrix-calculator", category: "Mathematics", subcategory: "Algebra", icon: "<svg fill='none' viewBox='0 0 24 24' stroke='currentColor' stroke-width='2'><path stroke-linecap='round' stroke-linejoin='round' d='M4 6h16v12H4V6z'></path></svg>", component: "MatrixCalculator" },
  { id: "fraction-calculator", title: "Fraction Calculator", description: "Add, subtract, multiply, and divide fractions.", slug: "fraction-calculator", category: "Mathematics", subcategory: "Basic Math", icon: "<svg fill='none' viewBox='0 0 24 24' stroke='currentColor' stroke-width='2'><path stroke-linecap='round' stroke-linejoin='round' d='M4 6h16v12H4V6z'></path></svg>", component: "FractionCalculator" },
  { id: "permutation-calculator", title: "Permutation Calculator (nPr)", description: "Calculate permutations.", slug: "permutation-calculator", category: "Mathematics", subcategory: "Statistics", icon: "<svg fill='none' viewBox='0 0 24 24' stroke='currentColor' stroke-width='2'><path stroke-linecap='round' stroke-linejoin='round' d='M4 6h16v12H4V6z'></path></svg>", formulaConfig: { inputs: [{ id: "n", label: "Total Objects (n)" }, { id: "r", label: "Selected Objects (r)" }], expression: "(function(n,r){ if(!Number.isInteger(n) || !Number.isInteger(r) || n<0 || r<0 || r>n) return 'Invalid'; let f=function(x){let r=1; for(let i=2;i<=x;i++) r*=i; return r;}; return f(n)/f(n-r); })(n,r)", outputLabel: "Permutations (nPr)" } },
  { id: "combination-calculator", title: "Combination Calculator (nCr)", description: "Calculate combinations.", slug: "combination-calculator", category: "Mathematics", subcategory: "Statistics", icon: "<svg fill='none' viewBox='0 0 24 24' stroke='currentColor' stroke-width='2'><path stroke-linecap='round' stroke-linejoin='round' d='M4 6h16v12H4V6z'></path></svg>", formulaConfig: { inputs: [{ id: "n", label: "Total Objects (n)" }, { id: "r", label: "Selected Objects (r)" }], expression: "(function(n,r){ if(!Number.isInteger(n) || !Number.isInteger(r) || n<0 || r<0 || r>n) return 'Invalid'; let f=function(x){let r=1; for(let i=2;i<=x;i++) r*=i; return r;}; return f(n)/(f(r)*f(n-r)); })(n,r)", outputLabel: "Combinations (nCr)" } },
  { id: "probability-calculator", title: "Probability Calculator", description: "Calculate the probability of events.", slug: "probability-calculator", category: "Mathematics", subcategory: "Statistics", icon: "<svg fill='none' viewBox='0 0 24 24' stroke='currentColor' stroke-width='2'><path stroke-linecap='round' stroke-linejoin='round' d='M4 6h16v12H4V6z'></path></svg>", component: "ProbabilityCalculator" },
  { id: "polynomial-calculator", title: "Polynomial Calculator", description: "Evaluate polynomial expressions.", slug: "polynomial-calculator", category: "Mathematics", subcategory: "Algebra", icon: "<svg fill='none' viewBox='0 0 24 24' stroke='currentColor' stroke-width='2'><path stroke-linecap='round' stroke-linejoin='round' d='M12 6v6m0 0v6m-6-6h12'></path></svg>", component: "PolynomialCalculator" }
];`;

content = content.replace(/\n];\s*$/, newTools + '\n];\n');
fs.writeFileSync(file, content, 'utf8');
