// @ts-check
import { defineConfig } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';

import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  site: 'https://studentkit.in',
  vite: {
    plugins: [tailwindcss()]
  },
  integrations: [sitemap()],
  redirects: {
    "/tools/marks-calculator": "/tools/percentage-calculator",
    "/tools/required-marks": "/tools/final-grade-calculator",
    "/tools/percentage-difference-calculator": "/tools/percentage-calculator",
    "/tools/relative-error-calculator": "/tools/percentage-calculator",
    "/tools/gcd-calculator": "/tools/lcm-calculator",
    "/tools/ohms-law-voltage": "/tools/ohms-law-calculator",
    "/tools/electrical-power-calculator": "/tools/ohms-law-calculator",
    "/tools/mirror-equation-calculator": "/tools/lens-equation-calculator",
    "/tools/boyles-law": "/tools/ideal-gas-law",
    "/tools/charles-law": "/tools/ideal-gas-law",
    "/tools/gay-lussacs-law": "/tools/ideal-gas-law",
    "/tools/combined-gas-law": "/tools/ideal-gas-law",
    "/tools/daltons-law": "/tools/ideal-gas-law",
    "/tools/graham-law-calculator": "/tools/ideal-gas-law",
    "/tools/molality-calculator": "/tools/molarity-calculator",
    "/tools/mass-percent-calculator": "/tools/molarity-calculator",
    "/tools/normality-calculator": "/tools/molarity-calculator",
    "/tools/ppm-calculator": "/tools/molarity-calculator",
    "/tools/poh-calculator": "/tools/ph-calculator",
    "/tools/hydrogen-ion-concentration": "/tools/ph-calculator",
    "/tools/hydroxide-ion-concentration": "/tools/ph-calculator",
    "/tools/pka-calculator": "/tools/ph-calculator",
    "/tools/pkb-calculator": "/tools/ph-calculator",
    "/tools/ka-calculator": "/tools/ph-calculator",
    "/tools/kb-calculator": "/tools/ph-calculator",
    "/tools/body-surface-area": "/tools/bmi-calculator",
    "/tools/waist-to-height-ratio": "/tools/bmi-calculator",
    "/tools/cell-organelles": "/tools/animal-cell",
    "/tools/cell-structure": "/tools/animal-cell",
    "/tools/eukaryotic-cell": "/tools/animal-cell",
    "/tools/prokaryotic-cell": "/tools/plant-cell",
    "/tools/cell-cycle": "/tools/mitosis-stages",
    "/tools/meiosis-stages": "/tools/mitosis-stages",
    "/tools/hardy-weinberg": "/tools/hardy-weinberg-calculator",
    "/tools/amino-acids": "/tools/amino-acid-reference",
    "/tools/transcription-reference": "/tools/central-dogma",
    "/tools/translation-reference": "/tools/central-dogma",
    "/tools/quartile-calculator": "/tools/five-number-summary",
    "/tools/iqr-calculator": "/tools/five-number-summary",
    "/tools/standard-error-calculator": "/tools/confidence-interval-calculator",
    "/tools/covariance-calculator": "/tools/linear-regression-calculator",
    "/tools/correlation-coefficient": "/tools/linear-regression-calculator",
    "/tools/regression-equation-calculator": "/tools/linear-regression-calculator",
    "/tools/r-squared-calculator": "/tools/linear-regression-calculator",
    "/tools/standard-normal-distribution": "/tools/normal-distribution-calculator",
    "/tools/logical-expression-evaluator": "/tools/truth-table-generator",
    "/tools/matrix-rank-calculator": "/tools/rref-calculator",
    "/tools/matrix-trace-calculator": "/tools/rref-calculator",
    "/tools/speed-calculator": "/tools/projectile-motion-calculator",
    "/tools/velocity-calculator": "/tools/projectile-motion-calculator",
    "/tools/acceleration-calculator": "/tools/projectile-motion-calculator",
    "/tools/work-calculator": "/tools/free-fall-calculator",
    "/tools/power-calculator": "/tools/ohms-law-calculator",
    "/tools/potential-energy-calculator": "/tools/free-fall-calculator",
    "/tools/kinetic-energy-calculator": "/tools/free-fall-calculator",
    "/tools/momentum-calculator": "/tools/free-fall-calculator",
    "/tools/impulse-calculator": "/tools/free-fall-calculator",
    "/tools/gravitational-potential-energy-calculator": "/tools/gravitational-force-calculator",
    "/tools/spring-potential-energy-calculator": "/tools/friction-calculator",
    "/tools/logistic-growth": "/tools/dna-sequence-analyzer",
    "/tools/doubling-time": "/tools/half-life-calculator",
    "/tools/quadratic-equation-solver": "/tools/prime-factorization-calculator",
    "/tools/second-derivative-calculator": "/tools/derivative-calculator",
    "/tools/partial-derivative-calculator": "/tools/derivative-calculator",
    "/tools/definite-integral-calculator": "/tools/integral-calculator",
    "/tools/indefinite-integral-calculator": "/tools/integral-calculator",
    "/tools/one-sided-limit-calculator": "/tools/limit-calculator",
    "/tools/infinite-limit-calculator": "/tools/limit-calculator",
    "/tools/right-triangle-calculator": "/tools/triangle-calculator",
    "/tools/triangle-area-calculator": "/tools/triangle-calculator",
    "/tools/half-life-first-order": "/tools/half-life-calculator",
    "/tools/half-life-nuclear": "/tools/half-life-calculator",
    "/tools/standard-cell-potential": "/tools/cell-potential-calculator",
    "/tools/nernst-equation": "/tools/cell-potential-calculator",
    "/tools/q-mc-delta-t": "/tools/calorimetry-calculator"
}
});
